name: GitHub_Action_CI

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Gradlew
          run: chmod +x ./gradlew

      - name: Lint
        run: ./gradlew ./gradlew -Pci --console=plain :app:lintDebug -PbuildDir=lint
        with:
          name: lint-debug.html
          path: app/lint/reports/

      - name: Build
        run: ./gradlew ./gradlew assembleDebug
        with:
          name: apk-debug.apk
          path: app/build/outputs/apk/debug/app-debug.apk

      - name: Run Test
        run: ./gradlew -Pci --console=plain :app:testDebug
